{% set name = "somoclu" %}
{% set version = "1.7.5" %}
{% set sha256 = "60d557d7c23ac4fa3fc16d3b86065b879d930351c07ffec8d60d1f02e868921e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1006
  skip: True  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - llvm-openmp  # [osx and c_compiler == "clang"]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - llvm-openmp  # [osx and c_compiler == "clang"]

test:
  imports:
    - somoclu

about:
  home: http://github.com/peterwittek/somoclu
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Massively parallel self-organizing maps: accelerate training on multicore CPUs and GPUs'
  doc_url: https://somoclu.readthedocs.org/
  dev_url: https://github.com/peterwittek/somoclu

extra:
  recipe-maintainers:
    - peterwittek
