{% set name = "somoclu" %}
{% set version = "1.7.6" %}
{% set sha256 = "3c3a7e54c3659ba214c644a0de0a4cc3fe55126a57c9c19920fa5609f5c8f664" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - llvm-openmp  # [osx and c_compiler == "clang"]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - llvm-openmp  # [osx and c_compiler == "clang"]

test:
  imports:
    - somoclu

about:
  home: http://github.com/peterwittek/somoclu
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Massively parallel self-organizing maps: accelerate training on multicore CPUs and GPUs'
  doc_url: https://somoclu.readthedocs.org/
  dev_url: https://github.com/peterwittek/somoclu

extra:
  recipe-maintainers:
    - xgdgsc
    - peterwittek
