appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AstHJu0gZuLW4FzJBjt+NcYshPZVZEt3rBoG1BqF7CAT0+9XmnC6bqlNcmxOjEbr4G+hqToWQANXhY7dV8X5tcucMMzXikQk6PZlFHmM/eaksQ8mQuNXvk709/pAgCJTLZkYiFiRTsRt4LpaleVGUVxSWyRVG5F457LKnh4ZQd2012PGio1z7S3rgo5f0tAi84lkxH4MjWBhTuX0VTUnm/t+iegoRiHx0DD7+XsWXCtG6Qe8N/cS0tHaFkYyuEhelDV7xbPPw69swqwjhQrVDk8jWftOyEUvg90083H/b1AgVoounaItKX51OcuucuPJejIjb6QCo+8RLzfvljQzIT/+qWNXM2Jwunw+o3YpP++NZD3FCIvHioRJnjhLfJMfXXXvLc7OSk1QC70RL5lZ2OtfG5JScaobWY+AIrC7fpKRWEIoSdSlKp7dEvqRNxFlfq9rFB+bWwby3x7IAtcp4+DqKGSFUf6YLGfjJ+uooBzhyuGwXtH5mjZxGU13JvhqNOnllBtvcq+snYhuDCcVpiMnfH0reub2MWkwdb545UNQr6cbUUGHUD5LwX4D7MPXlOOKlogETp9EsFqeTkDv7JoA5FqRgPUNjL1cYvlnJrLWiQJJcb5pMonIDIfnmfx81MzMjtljvZRUr7coMXPGNlnyFri3xBvHIqkk3zypFow=}
